name: gen gitea contribution
on:
  schedule:
    - cron: "0 */24 * * *"
jobs:
  generate:
    runs-on: ubuntu-latest
    env:
      GITEA_USER: ${{ secrets.GITEA_USER }}
      GITEA_URL: ${{ secrets.GITEA_URL }}
      GITEA_TOKEN: ${{ secrets.GITEA_TOKEN }}
    steps:
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.11"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run script
        run: python .\src\main.py
      - name: Commit
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git commit -a -m "Update Gitea Contribution"
      - name: Push
        uses: ad-m/github-push-action@master
        with:
          branch: ${{ github.head_ref }}
